#include <stdlib.h>
#include <stdio.h> 

#include "read_write.h"

void write_pgm_image( void *image, int size, const char *image_name)
/*
 * image        : a pointer to the memory region that contains the image
 * size         : lato of the square image
 * image_name   : the name of the file to be written
 */
{
    // size is the same for x and y
    // maxval is 1 as we only store black or white

    FILE* image_file; 
    image_file = fopen(image_name, "w");

    // header
    fprintf(image_file, "P5\n# generated by\n# put here your name\n%d %d\n%d\n", size, size, 1);
  
    // writing file
    fwrite( image, 1, size*size, image_file);  

    fclose(image_file); 
    return;
}

// I tried to suit this function for xsize==ysize and maxval==1
// but it didn't work properly and it is not worth my time

/*
 * image        : a pointer to the pointer that will contain the image
 * maxval       : a pointer to the int that will store the maximum intensity in the image
 * xsize, ysize : pointers to the x and y sizes
 * image_name   : the name of the file to be read
 */

void read_pgm_image( void **image, int *maxval, int *xsize, int *ysize, const char *image_name)
{
    FILE* image_file; 
    image_file = fopen(image_name, "r"); 

    *image = NULL;
    *xsize = *ysize = *maxval = 0;
  
    char    MagicN[2];
    char   *line = NULL;
    size_t  k, n = 0;
  
    // get the Magic Number
    k = fscanf(image_file, "%2s%*c", MagicN );

    // skip all the comments
    k = getline( &line, &n, image_file);
    while ( (k > 0) && (line[0]=='#') )
        k = getline( &line, &n, image_file);

    if (k > 0)
    {
        k = sscanf(line, "%d%*c%d%*c%d%*c", xsize, ysize, maxval);
        if ( k < 3 )
	        fscanf(image_file, "%d%*c", maxval);
    }
    else
    {
        *maxval = -1; // this is the signal that there was an I/O error
                      // while reading the image header
        free( line );
        return;
    }
    free( line );
    
    int color_depth = 1 + ( *maxval > 255 );
    unsigned int size = *xsize * *ysize * color_depth;
    
    if ( (*image = (char*)malloc( size )) == NULL )
    {
        fclose(image_file);
        *maxval = -2;         // this is the signal that memory was insufficient
        *xsize  = 0;
        *ysize  = 0;
        return;
    }
  
    if ( fread( *image, 1, size, image_file) != size )
    {
        free( image );
        image   = NULL;
        *maxval = -3;         // this is the signal that there was an i/o error
        *xsize  = 0;
        *ysize  = 0;
    }  

    fclose(image_file);
    return;
}